### ISSUE TITLE
Pre-architecture discussion

### ISSUE THREAD

**Issue by hadasz** [ConsenSys/web3studio-bootleg#1]
Questions to consider before architecture can be drawn up:
1) How will tokens be designed? Will each specific show and band get their own type of token? Will we create a generalized "bootleg" token that can be specified to specific bands + shows  or will each token be its  own type completely?  

2) Can a token that accesses one band be exchanged  for that of another band? Can tokens  associated  to one concert be exchanged with tokens associated  with a different  concert?

3) Security Design: How will a  token give access to a video? 

4) Where  will  the content  live? Who will be responsible for hosting  the video and making sure the correct amount of people are  able to download it?

5) Do we want to  build a front end?

6) How to prototype/test? Will test net be sufficient?

7) Can this work on Ethereum alone or will a side chain be needed?

**Comment by hadasz** [comment]
Thoughts on Questions above (numbers correspond to question number)
1) ERC is a template of a smart contract. The re-usable part of this is the "pay it backward" model. So we want one re-usable smart contract template that maintains a token (implemented as a mapping between public addresses and balance, and any time a trade happens, splits up the money between everyone that currently exists in the mapping. **How does ERC20 facilitate trades? How do other smart contracts with DAO's facilitate trades?**

For bootleg specifically, we need to streamline a way for bands to manage many "pay it backward" smart contracts, one for each video they give license to. Maybe write one smart contract that deploys smart contracts with our ERC and routes trades to the appropriate smart contract. 

2)If inter-band trading were possible, we would need one meta smart contract that handles all bands. 

3)Something will be sent to the person receiving a token that gives them access to the video. To  ensure that this person cannot transfer this value to another person off chain, the value should need to be used in conjunction with that persons Ethereum private key. That way, if a person wanted to share it with an unauthorized entity, they would be forced to give up their private key.

**Knowledge that exists but need to learn**
-   How do trades for tokens take place in ERC20? Does the person selling the token send an agreement to the smart contract that includes agreed upon price, and how many tokens they are willing to give for that price? And then the person buying the tokens sends Ether to the smart contract and then the smart contract facilitates the trade by deducting from one person's balance and adding to the others?

**Decisions we need to make**
-  Will there be a such thing as partial  tokens? Like, can I have 10 tokens for 1 video, and each of the 10 tokens gives me 10 minutes of the video? Or is it all or nothing and each token corresponds to the right to see the entire video?

- When somebody receives a token, they need to be sent something that gives them a right to watch the video. Will this be apart of the smart contract template or something that needs to be added individually? I think it should be added to the template, but that means we need a way to abstract away the cryptography aspect

**Comment by humbitious** [comment]
So a Bootleg token (and the associated smart contract) consists of the following attributes (in my imagination):

1) Current owner;
2) Issue # (indicating the group that this token belongs to... the 100 in "#33 of 100")
3) Total # issued (e.g., 100...or 1...or 100000)
4) The # of this particular "Print" (need a name for this): e.g., #33
5) The Band issuing (and their ID?)
6) The specific concert (and its ID?)
7) Details of the concert and other metacontent for marketing and other identification purposes...maybe, for example, genre of concert? maybe the tags things like pandora and spotify use to classify the band or the songs?...oh, and probably which songs were played?
8) ID of the bootlegger
9) Public Keys of all previous holders (provenance)

...more to come.

**Comment by humbitious** [comment]
I would say that inter-band trading and similar should not be enabled.  Keep it simple(?) If you want to buy a different bootleg, go buy it. 

This does cast into sharp detail the reality of this pattern: once a holder always a holder. As AlexM and MikeC suggested, if you can sell your holding, you no longer have an incentive against pirating...though perhaps there are other ways (openlaw?) to tamp that down.

So I'd probably argue that both cross-bootleg trading and fractional holding should not be supported in the spec, but I'm not concrete in that pov yet.  (This shouldn't be the kind of token where fractional shares matter, right?  In a way, it is by definition a fractional holding, because every sale distributes money to holders according to a fractional schedule.)  As I write this, thinking that a look into current methods for handling fractional shares would be instructive.

**Comment by hadasz** [comment]
In terms of selling your holding - what if there is was a cryptographic way to revoke someones access to the video? Or maybe that wouldn't fix anything because someone could just screen record it, or download it while its decrypted? 
If it is "once a holding, always a holding" mentality, then what is creating the scarcity? Is it that there is only a certain amount of times that rights can be shared? Does each person have a quota on how many times they can share a video? How are these quotas decided?

**Comment by breakpointer** [comment]
My answers to the questions... 

**_Q 1. How will tokens be designed? Will each specific show and band get their own type of token? Will we create a generalized "bootleg" token that can be specified to specific bands + shows or will each token be its own type completely?_**
A: There are actually two very different topics in this list questions. How the tokens will be designed is quite technical and I'll address that separately. WRT to the other questions, they are more about use of this new token standard.  My initial thinking around this is driven from the perspective of if Bootleg was a company/entity for real. They'd be motivated to establish the Bootleg:copyright: brand among artists and concert-goers as being legit. Buying a (capital B) Bootleg would give you, the purchaser, the confidence that scarcity was enforced, value of the purchased was (relatively) stable, and that quality/uniformity of the recording was to a certain acceptable bar. In that sense, Bootleg the company would implement their version of the ERC-pay-it-backward and create their implementation. Their BLEG token would be available for use by all artists across all shows for all time.

**_Q 2. Can a token that accesses one band be exchanged for that of another band? Can tokens associated to one concert be exchanged with tokens associated with a different concert?_**
A: No, I think this would complicate things. Trades could be managed by the Bootleg system but it would be, behind the scenes, the sale of one BLEG and the purchase of another. Perhaps managed in the equivalent of a two part transaction (assuming this is possible?).

**_Q 3. Security Design: How will a token give access to a video?_**
A: Not sure at this point. Ideally, we could find a way to make the purchasing and owning the token the valuable bit on its own and not couple it to the source media. If the owning of the token is the ownership of the Bootleg media I'm wondering about the scenario where someone buys the Bootleg token, downloads the media and say, up-samples it to 8k (or whatever is the popular viewing resolution in the future). Does possessing the token allow you the right to make modifications to the media? Is the media locked down in it's original form for all eternity? This will need quite a bit more thought.

**_Q 4. Where will the content live? Who will be responsible for hosting the video and making sure the correct amount of people are able to download it?_**
A: Related to Q3 in some ways. Bootleg the company would pay for hosting the content files. Their should be a transaction fee for each BLEG token, this transaction fee would/should cover the costs of hosting the file (or at least the master copy of the file uploaded by the original bootlegger). In this system I'd imagine (as a courtesy) the seller of the bootleg could also provide the media files. The validity of the media file provided by the bootleg seller would be provided by the encryption scheme used to protect the content.

**_Q 5. Do we want to build a front end?_**
A: Maybe? It might be fun to build out the bootleg inventory/for-sale pages or the artist interface, if it helped us think through certain scenarios. The backend is far more interesting IMHO. 

**_Q 6. How to prototype/test? Will test net be sufficient?_**
A: I think test net will have to be. Otherwise we'll have to come up with some other private chain for testing purposes. 

Q 7. Can this work on Ethereum alone or will a side chain be needed?
A:

**Comment by breakpointer** [comment]
> Yes - it is already a fractional holding, in that a token is a fraction of the equity, and the person holding it, gets a fraction of each payment. I was thinking more along the lines of if the token should be a fraction of the video. Which enables a person to have less of the video for less money, and get less money each time holders are paid out. I agree that's definitely not necessary for the first rendition. We should keep it as simple as possible so it is as extensible as possible. Was just splashing some paint.

Interesting idea @hadasz but I think for simplicity we should not go down this path.

**Comment by tjchmielewski** [comment]
Soooo the Pay-It-Backward-Model. Bootlegger films video, gets approved to sell. Sells to a fan. We'll call them "fan1". Bootlegger gets? and Band Gets?
Fan1 sells their rights to it. The Band gets? The Bootlegger gets? Fan1 gets?
Fan2 sells their right to fan3. The Band gets? The Bootlegger gets? Fan1 gets? Fan2 gets?

**Comment by tjchmielewski** [comment]
Also, I would suggest, if you reference something/someone in here, please put the link of the site or screenshot/copy and paste the conversation you are speaking about. I believe there is some disconnect on this team with what is common knowledge given from outside teams and what is common knowledge amongst us 5. Let's not assume anything.

**Comment by humbitious** [comment]
"Q 3. Security Design: How will a token give access to a video?
A: Not sure at this point. Ideally, we could find a way to make the purchasing and owning the token the valuable bit on its own and not couple it to the source media. If the owning of the token is the ownership of the Bootleg media I'm wondering about the scenario where someone buys the Bootleg token, downloads the media and say, up-samples it to 8k (or whatever is the popular viewing resolution in the future). Granted this is a "happy path" but does possessing the token allow you the right to make modifications to the media? Is the media locked down in it's original form for all eternity? The "un-happy" path is someone pirating the video and putting it online. We need to assume this will happen and not tie the value of the token to the scarcity of the media file. This will need quite a bit more thought."

My thinking on this was that the token and the private keys combined are a very small part of the video file which unscrambles/decrypts. Another way to handle this is to put the official file (encrypted) on traditional or storj-like service and the token/priv-key is used to access and decrypt(?)  

Two questions for the devKit (brian...you are in my head that devKit isn't the right name, but imaginationKit isn't doing it for me...gotta think about this):

1) Should the Minimally Viable "Prototype" deal with this side of the story? If not, how to make it easy to add.

2) How to structure the architecture of the token/contract (and possibly an off-chain secure Oracle on something like ChainLink or MSFT) to support the following: 1) Main video file should be rendered unusuable in some way without something the token-holder (and possibly the past token holders) have.  2) Transaction on chain of token payload is probably necessary but insufficient as an unlocking mechanism, because anyone could copy it from the public ledger (and putting it on private ledger is just stupid, QED).  3) If we used the private key plus payload of the token (plus a nonce to prevent repeat-attack?), then we'd need a way to a) allow a new holder to be added (not decentralized service solves?); b) allow option of old holders either no longer being able to unlock video or that old holders may continue to unlock...if the latter, must be all-or-nothing or some way to include some and not others?

**Comment by breakpointer** [comment]
>>> I was wondering if it Is possible to have the act of decrypting the video embed the persons private key into their version of it (using something like stenography where the last bit of each RGB pixel is one bit of the private key). This may be farfetched But the main idea is just to make sure that no one will want to share the video outside the system.

This is interesting... as you have described it the private key is collateral for "good behavior" in the system. Conceptually I like it but in practice sharing my private key to be embedded in some other set of files I don't have direct control over might be a non-starter. How do I know the stenographic approach (for example) is secure? What if it is compromised? 
Assuming this was the only way to get the bootleg token and I had to provide my private key, I would probably create a second wallet and private key (since you can only have one IIRC unlike public keys where you can generate sub-keys to use). I might create a new one for each bootleg I purchase. At this point with my new wallet/private key I'm less likely to care about it as much and then it becomes less valuable (to me) as collateral which would undermine the reason (assuming I understand the premise) to provide collateral in the first place? Right?

**Comment by breakpointer** [comment]
I think this was a good pass at the questions we posed initially. Going to close the issue as done. Re-open if you want to continue the discussion.

**Comment by hadasz** [comment]
Agree to closing it - just to clarify my thoughts about it - was thinking the embedding of the private key in the video would only happen client-side as a byproduct of decrypting it. Science fiction but I understand that sending private key to a third party even if It’s encrypted is a non starter
