### ISSUE TITLE
SxSW Presentation

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-bootleg#8]
## Overview

As an attendee at SXSW, I want to learn about bootleg and web3studio, so that we inspire entrepreneurs and developers, create awareness of Consensys and Web3Studio, and encourage the community to reach out to us and use our material or ask questions about blockchain or our knowledge of music in the bootleg-y space.

### Questions

- We have a compelling story, what's the best way to tell it so that it is novel and memorable?
- What tracks exist and can we get on? Do we fit into one?

### Assumptions

- Our audience will be developers, entrepreneurs and/or tech-aware people.
    - If this changes, we need to adjust our story

### Acceptance

- We present something at SXSW, or get rejected and sit in the audience.

## Story Drafts

- [ ] As Amanda and Jory, I need to see proof that Bootleg and Web3Studio will "kill" at the event, so that we can be confident that the cost and opportunity cost decision are solidly in favor of including them. 
    - Create a slide deck (Outline, Copy, Slide Creation, Illustrations and/or Photo gathering, Animation) 
- [ ] Practice, practice, practice

**Comment by tjchmielewski** [comment]
Tell a compelling story via a presentation at a major conference, so that we inspire entrepreneurs and developers, create awareness of Consensys and Web3Studio, and encourage the community to reach out to us and use our material or ask questions. 

Questions: We have a compelling story, what's the best way to tell it so that it is novel and memorable?

Assumptions: Our audience will be developers, entrepreneurs and/or tech-aware people.

Acceptance: Nothing but the best

Tasks: Outline, Copy, Slide Creation, Illustrations and/or Photo gathering, Animation?, Practice
