### ISSUE TITLE
Bootleg Experience

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-bootleg#9]
## Overview

As an Entrepreneur looking to build something like bootleg, I want to have a collection of published research and experience maps, so that I can build my experience better and quicker.

### Questions

- Not sure how the performer/ticketing/venue process works. 
- Unsure about copyright laws (who owns the rights... the performer or the videographer or both? What if it's a cover band). 
- How do we make this attractive to performers? 
- Who sets the price? 
- How does the pay-it-backwards model work? 
- Can it be altered under new conditions agreed upon by performer and videographer?

### Assumptions

- Fans will buy footage of shows they have been to. 
- The scarcity of the footage will make this more attractive and valuable.

### Acceptance

- Synthesis of Journey/Research will be present in the devkit

## Story Draft

- [ ] Customer Interviews. 
- [ ] Performer Journey. 
- [ ] Videographer Journey. 
- [ ] Fan Journey. 
- [ ] Storyboards of all 3. 
- [ ] Wireframes. 
- [ ] Light Prototype.

**Comment by tjchmielewski** [comment]
Create assets of the end-to-end bootleg experience, so that we can paint a realistic picture of what a life with bootleg would look like and test with actual users. 

Q. Not sure how the performer/ticketing/venue process works. Unsure about copyright laws (who owns the rights... the performer or the videographer or both? What if it's a cover band). How do we make this attractive to performers? Who sets the price? How does the pay-it-backwards model work? Can it be altered under new conditions agreed upon by performer and videographer?

Assumptions: Fans will buy footage of shows they have been to. The scarcity of the footage will make this more attractive and valuable.  

Acceptance: Viewers heads exploding upon witnessing the greatness.

Tasks. Customer Interviews. Performer Journey. Videographer Journey. Fan Journey. Storyboards of all 3. Wireframes. Light Prototype. Illustrations. Presentation.

**Comment by breakpointer** [comment]
Done? https://consensys.net/web3studio/bootleg/
